import graphene
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, NumberAttribute
from utils import Utils
import logging


class config:
    conf = Utils.load_config("config.json")


class claveS(graphene.InputObjectType):
    S = graphene.String()


class claveoS(graphene.InputObjectType):
    S = graphene.String()


class claveN(graphene.InputObjectType):
    S = graphene.Int()


class claveoN(graphene.InputObjectType):
    S = graphene.Int()


class LastEvaluatedKeyPreaprobadosConsumoCombos(graphene.InputObjectType):
    clave = claveS()
    clave_ordenamiento = claveoS()

class PreaprobadosConsumoCombos(Model):
    class Meta:
        table_name = config.conf['preaprobados_consumo_combos_table']
        # Specifies the region
        region = config.conf['region']
        # Specifies the write capacity
        write_capacity_units = config.conf['write_capacity_units']
        # Specifies the read capacity
        read_capacity_units = config.conf['read_capacity_units']

    clave = UnicodeAttribute(hash_key=True)
    clave_ordenamiento = UnicodeAttribute(range_key=True)
    tipoid = UnicodeAttribute(null=True, attr_name="tipoid")
    num_doc = UnicodeAttribute(null=True, attr_name="id")
    nombre_cliente = UnicodeAttribute(null=True, attr_name="nombre_cliente")
    segmento = UnicodeAttribute(null=True, attr_name="segmento")
    ejecutivo = UnicodeAttribute(null=True, attr_name="ejecutivo")
    tel1 = NumberAttribute(null=True, attr_name="tel1")
    tel2 = NumberAttribute(null=True, attr_name="tel2")
    tel3 = NumberAttribute(null=True, attr_name="tel3")
    tel4 = NumberAttribute(null=True, attr_name="tel4")
    tel5 = NumberAttribute(null=True, attr_name="tel5")
    tel6 = NumberAttribute(null=True, attr_name="tel6")
    tel7 = NumberAttribute(null=True, attr_name="tel7")
    tel8 = NumberAttribute(null=True, attr_name="tel8")
    tel9 = NumberAttribute(null=True, attr_name="tel9")
    tel10 = NumberAttribute(null=True, attr_name="tel10")
    ciudad_contacto = UnicodeAttribute(null=True, attr_name="ciudad_contacto")
    cupo_asigando_crediagil = UnicodeAttribute(null=True, attr_name="cupo_asigando_crediagil")
    num_prestamo = NumberAttribute(null=True, attr_name="num_prestamo")
    valor_desembolso = NumberAttribute(null=True, attr_name="valor_desembolso")
    tipo_plan = UnicodeAttribute(null=True, attr_name="tipo_plan")
    producto = UnicodeAttribute(null=True, attr_name="producto")
    plazo_actual = NumberAttribute(null=True, attr_name="plazo_actual")
    frecuencia_pago = UnicodeAttribute(null=True, attr_name="frecuencia_pago")
    tasa_namv = NumberAttribute(null=True, attr_name="tasa_namv")
    tipo_de_tasa = UnicodeAttribute(null=True, attr_name="tipo_de_tasa")
    fecha_desembolso = UnicodeAttribute(null=True, attr_name="fecha_desembolso")
    fecha_vencimiento = UnicodeAttribute(null=True, attr_name="fecha_vencimiento")
    nueva_fecha_vencimiento = UnicodeAttribute(null=True, attr_name="nueva_fecha_vencimiento")
    saldo_neto = NumberAttribute(null=True, attr_name="saldo_neto")
    cuota_regular = NumberAttribute(null=True, attr_name="cuota_regular")
    cuota_incluye_seguro = UnicodeAttribute(null=True, attr_name="cuota_incluye_seguro")
    cuota_fija_k = NumberAttribute(null=True, attr_name="cuota_fija_k")
    tipo_de_cuota = UnicodeAttribute(null=True, attr_name="tipo_de_cuota")
    intereses_pendientes = NumberAttribute(null=True, attr_name="intereses_pendientes")
    saldo_sg_vida = NumberAttribute(null=True, attr_name="saldo_sg_vida")
    fecha_prox_pago = UnicodeAttribute(null=True, attr_name="fecha_prox_pago")
    nueva_fecha_prox_pago = UnicodeAttribute(null=True, attr_name="nueva_fecha_prox_pago")
    fecha_ultimo_pago = UnicodeAttribute(null=True, attr_name="fecha_ultimo_pago")
    num_cuotas_faltantes = NumberAttribute(null=True, attr_name="num_cuotas_faltantes")
    plazo_min = NumberAttribute(null=True, attr_name="plazo_min")
    plazo_max = NumberAttribute(null=True, attr_name="plazo_max")
    ampliacion_plazo_meses = NumberAttribute(null=True, attr_name="ampliacion_plazo_meses")
    max_periodo_de_gracia_o_prorroga = NumberAttribute(null=True, attr_name="max_periodo_de_gracia_o_prorroga")
    meses_prorroga_elegidos = NumberAttribute(null=True, attr_name="meses_prorroga_elegidos")
    nuevo_plazo_total_en_meses = UnicodeAttribute(null=True, attr_name="nuevo_plazo_total_en_meses")
    mes_pago_fng = UnicodeAttribute(null=True, attr_name="mes_pago_fng")
    monto_fng = UnicodeAttribute(null=True, attr_name="monto_fng")
    mes_pago_comision_mipyme = UnicodeAttribute(null=True, attr_name="mes_pago_comision_mipyme")
    monto_comision_mipyme = NumberAttribute(null=True, attr_name="monto_comision_mipyme")
    frec_mipyme = UnicodeAttribute(null=True, attr_name="frec_mipyme")
    comision_mipyme_fng = UnicodeAttribute(null=True, attr_name="comision_mipyme_fng")
    cuota_anterior = NumberAttribute(null=True, attr_name="cuota_anterior")
    vlr_cuota_actual = NumberAttribute(null=True, attr_name="vlr_cuota_actual")
    nueva_cuota_sin_otros_conceptos = UnicodeAttribute(null=True, attr_name="nueva_cuota_sin_otros_conceptos")
    nueva_cuota_a_capital = UnicodeAttribute(null=True, attr_name="nueva_cuota_a_capital")
    nueva_cuota_total = UnicodeAttribute(null=True, attr_name="nueva_cuota_total")
    disminucion_de_cuota = UnicodeAttribute(null=True, attr_name="disminucion_de_cuota")
    nueva_cuota_sistema = UnicodeAttribute(null=True, attr_name="nueva_cuota_sistema")
    marca_riesgos = UnicodeAttribute(null=True, attr_name="marca_riesgos")
    genero = UnicodeAttribute(null=True, attr_name="genero")
    fecha_nacimiento = NumberAttribute(null=True, attr_name="fecha_nacimiento")
    email_1 = UnicodeAttribute(null=True, attr_name="email_1")
    email_2 = UnicodeAttribute(null=True, attr_name="email_2")
    nueva_g = UnicodeAttribute(null=True, attr_name="nueva_g")
    region = UnicodeAttribute(null=True, attr_name="region")
    codigo_seg_vida = NumberAttribute(null=True, attr_name="codigo_seg_vida")
    extraprima_seguro = NumberAttribute(null=True, attr_name="extraprima_seguro")
    factor_seguro = NumberAttribute(null=True, attr_name="factor_seguro")
    seguro_desempleo = NumberAttribute(null=True, attr_name="seguro_desempleo")
    prob = UnicodeAttribute(null=True, attr_name="prob")
    televentas_habeas_data = UnicodeAttribute(null=True, attr_name="televentas_habeas_data")
    mail_habeas_data = UnicodeAttribute(null=True, attr_name="mail_habeas_data")
    sms_habeas_data = UnicodeAttribute(null=True, attr_name="sms_habeas_data")
    departamento = UnicodeAttribute(null=True, attr_name="departamento")
    aliado = UnicodeAttribute(null=True, attr_name="aliado")
    base = UnicodeAttribute(null=True, attr_name="base")
    opcion_1 = UnicodeAttribute(null=True, attr_name="opcion_1")
    opcion_2 = UnicodeAttribute(null=True, attr_name="opcion_2")
    prioridad_creditos = NumberAttribute(null=True, attr_name="prioridad_creditos")
    fecha_proyprox_pago = NumberAttribute(null=True, attr_name="fecha_proyprox_pago")
    redescuento = NumberAttribute(null=True, attr_name="redescuento")
    concepto_distribucion1 = NumberAttribute(null=True, attr_name="concepto_distribucion1")
    conector_distribucion1 = UnicodeAttribute(null=True, attr_name="conector_distribucion1")
    concepto_distribucion2 = NumberAttribute(null=True, attr_name="concepto_distribucion2")
    conector_distribucion2 = UnicodeAttribute(null=True, attr_name="conector_distribucion2")
    concepto_distribucion3 = NumberAttribute(null=True, attr_name="concepto_distribucion3")
    conector_distribucion3 = UnicodeAttribute(null=True, attr_name="conector_distribucion3")
    concepto_distribucion4 = NumberAttribute(null=True, attr_name="concepto_distribucion4")
    conector_distribucion4 = UnicodeAttribute(null=True, attr_name="conector_distribucion4")
    concepto_distribucion5 = NumberAttribute(null=True, attr_name="concepto_distribucion5")
    conector_distribucion5 = UnicodeAttribute(null=True, attr_name="conector_distribucion5")
    concepto_distribucion6 = NumberAttribute(null=True, attr_name="concepto_distribucion6")
    conector_distribucion6 = UnicodeAttribute(null=True, attr_name="conector_distribucion6")
    concepto_distribucion7 = NumberAttribute(null=True, attr_name="concepto_distribucion7")
    conector_distribucion7 = UnicodeAttribute(null=True, attr_name="conector_distribucion7")
    concepto_distribucion8 = NumberAttribute(null=True, attr_name="concepto_distribucion8")
    conector_distribucion8 = UnicodeAttribute(null=True, attr_name="conector_distribucion8")
    concepto_distribucion9 = NumberAttribute(null=True, attr_name="concepto_distribucion9")
    estado = UnicodeAttribute(null=True, attr_name="estado")
    base_aliados = UnicodeAttribute(null=True, attr_name="base_aliados")
    nombre = UnicodeAttribute(null=True, attr_name="nombre")
    grupo = UnicodeAttribute(null=True, attr_name="grupo")
    perfil = UnicodeAttribute(null=True, attr_name="perfil")
    cod_abogado = UnicodeAttribute(null=True, attr_name="cod_abogado")
    cod_abogado_para = UnicodeAttribute(null=True, attr_name="cod_abogado_para")
    dias_mora = NumberAttribute(null=True, attr_name="dias_mora")
    nombre_para = UnicodeAttribute(null=True, attr_name="nombre_para")
    grupo_para = UnicodeAttribute(null=True, attr_name="grupo_para")
    perfil_para = UnicodeAttribute(null=True, attr_name="perfil_para")
    cobro_juridico = UnicodeAttribute(null=True, attr_name="cobro_juridico")
    fuente = UnicodeAttribute(null=True, attr_name="fuente")
    cnt_dias_mora = NumberAttribute(null=True, attr_name="cnt_dias_mora")
    consdocdeu = NumberAttribute(null=True, attr_name="consdocdeu")
    nueva_marca = UnicodeAttribute(null=True, attr_name="nueva_marca")
    venezolanos = UnicodeAttribute(null=True, attr_name="venezolanos")
    canal_rpc_semana = UnicodeAttribute(null=True, attr_name="canal_rpc_semana")
    exclusion_rpc = UnicodeAttribute(null=True, attr_name="exclusion_rpc")
    exclusion_lc = UnicodeAttribute(null=True, attr_name="exclusion_lc")
    novedad = UnicodeAttribute(null=True, attr_name="novedad")
    alternativa_aplicada_agr = UnicodeAttribute(null=True, attr_name="alternativa_aplicada_agr")
    marca_agrupada_rgo = UnicodeAttribute(null=True, attr_name="marca_agrupada_rgo")
    producto_agrupado_origen = UnicodeAttribute(null=True, attr_name="producto_agrupado_origen")
    f_aplicacion = NumberAttribute(null=True, attr_name="f_aplicacion")
    bpo = UnicodeAttribute(null=True, attr_name="bpo")
    exclusion_alt = UnicodeAttribute(null=True, attr_name="exclusion_alt")
    activo = NumberAttribute(null=True, attr_name="activo")
    year = NumberAttribute(null=True, attr_name="year")
    month = NumberAttribute(null=True, attr_name="month")
    day = NumberAttribute(null=True, attr_name="day")
    updated = NumberAttribute(null=True, attr_name="updated")
    modificacion_crud = NumberAttribute(null=True, attr_name="modificacion_crud")


def get_preaprobados_consumo_combos( clave , clave_ordenamiento , limit = 100, ascendente = True, last_evaluated_key = None):

    if config.conf["tracklogs"]:
        logging.info("Consulta get_preaprobados_consumo_combos con parametros: clave={}".format(clave))

    if clave_ordenamiento is not None:
        result = PreaprobadosConsumoCombos.query(hash_key = clave , range_key_condition = PreaprobadosConsumoCombos.clave_ordenamiento.startswith(clave_ordenamiento), filter_condition=PreaprobadosConsumoCombos.activo==1, limit=limit, scan_index_forward=ascendente,  last_evaluated_key=last_evaluated_key)
    else:
        result = PreaprobadosConsumoCombos.query( hash_key = clave , filter_condition=PreaprobadosConsumoCombos.activo==1, limit=limit, scan_index_forward=ascendente,  last_evaluated_key=last_evaluated_key)
    
    return list(result)


# class PreaprobadosConsumoCombosDataInput(graphene.InputObjectType):
#     clave = graphene.String()
#     clave_ordenamiento = graphene.String()
#     tipoid = graphene.String()
#     id = graphene.String()
#     nombre_cliente = graphene.String()
#     segmento = graphene.String()
#     ejecutivo = graphene.String()
#     tel1 = graphene.Int()
#     tel2 = graphene.Int()
#     tel3 = graphene.Int()
#     tel4 = graphene.Int()
#     tel5 = graphene.Int()
#     tel6 = graphene.Int()
#     tel7 = graphene.Int()
#     tel8 = graphene.Int()
#     tel9 = graphene.Int()
#     tel10 = graphene.Int()
#     ciudad_contacto = graphene.String()
#     cupo_asigando_crediagil = graphene.String()
#     num_prestamo = graphene.Float()
#     valor_desembolso = graphene.Float()
#     tipo_plan = graphene.String()
#     producto = graphene.String()
#     plazo_actual = graphene.Float()
#     frecuencia_pago = graphene.String()
#     tasa_namv = graphene.Float()
#     tipo_de_tasa = graphene.String()
#     fecha_desembolso = graphene.String()
#     fecha_vencimiento = graphene.String()
#     nueva_fecha_vencimiento = graphene.String()
#     saldo_neto = graphene.Float()
#     cuota_regular = graphene.Float()
#     cuota_incluye_seguro = graphene.String()
#     cuota_fija_k = graphene.Float()
#     tipo_de_cuota = graphene.String()
#     intereses_pendientes = graphene.Float()
#     saldo_sg_vida = graphene.Float()
#     fecha_prox_pago = graphene.String()
#     nueva_fecha_prox_pago = graphene.String()
#     fecha_ultimo_pago = graphene.String()
#     num_cuotas_faltantes = graphene.Int()
#     plazo_min = graphene.Int()
#     plazo_max = graphene.Int()
#     ampliacion_plazo_meses = graphene.Int()
#     max_periodo_de_gracia_o_prorroga = graphene.Int()
#     meses_prorroga_elegidos = graphene.Int()
#     nuevo_plazo_total_en_meses = graphene.String()
#     mes_pago_fng = graphene.String()
#     monto_fng = graphene.String()
#     mes_pago_comision_mipyme = graphene.String()
#     monto_comision_mipyme = graphene.Float()
#     frec_mipyme = graphene.String()
#     comision_mipyme_fng = graphene.String()
#     cuota_anterior = graphene.Float()
#     vlr_cuota_actual = graphene.Float()
#     nueva_cuota_sin_otros_conceptos = graphene.String()
#     nueva_cuota_a_capital = graphene.String()
#     nueva_cuota_total = graphene.String()
#     disminucion_de_cuota = graphene.String()
#     nueva_cuota_sistema = graphene.String()
#     marca_riesgos = graphene.String()
#     genero = graphene.String()
#     fecha_nacimiento = graphene.Float()
#     email_1 = graphene.String()
#     email_2 = graphene.String()
#     nueva_g = graphene.String()
#     region = graphene.String()
#     codigo_seg_vida = graphene.Int()
#     extraprima_seguro = graphene.Float()
#     factor_seguro = graphene.Float()
#     seguro_desempleo = graphene.Float()
#     prob = graphene.String()
#     televentas_habeas_data = graphene.String()
#     mail_habeas_data = graphene.String()
#     sms_habeas_data = graphene.String()
#     departamento = graphene.String()
#     aliado = graphene.String()
#     base = graphene.String()
#     opcion_1 = graphene.String()
#     opcion_2 = graphene.String()
#     prioridad_creditos = graphene.Int()
#     fecha_proyprox_pago = graphene.Float()
#     redescuento = graphene.Int()
#     concepto_distribucion1 = graphene.Float()
#     conector_distribucion1 = graphene.String()
#     concepto_distribucion2 = graphene.Float()
#     conector_distribucion2 = graphene.String()
#     concepto_distribucion3 = graphene.Float()
#     conector_distribucion3 = graphene.String()
#     concepto_distribucion4 = graphene.Float()
#     conector_distribucion4 = graphene.String()
#     concepto_distribucion5 = graphene.Float()
#     conector_distribucion5 = graphene.String()
#     concepto_distribucion6 = graphene.Float()
#     conector_distribucion6 = graphene.String()
#     concepto_distribucion7 = graphene.Float()
#     conector_distribucion7 = graphene.String()
#     concepto_distribucion8 = graphene.Float()
#     conector_distribucion8 = graphene.String()
#     concepto_distribucion9 = graphene.Float()
#     estado = graphene.String()
#     base_aliados = graphene.String()
#     nombre = graphene.String()
#     grupo = graphene.String()
#     perfil = graphene.String()
#     cod_abogado = graphene.String()
#     cod_abogado_para = graphene.String()
#     dias_mora = graphene.Int()
#     nombre_para = graphene.String()
#     grupo_para = graphene.String()
#     perfil_para = graphene.String()
#     cobro_juridico = graphene.String()
#     fuente = graphene.String()
#     cnt_dias_mora = graphene.Float()
#     consdocdeu = graphene.Int()
#     nueva_marca = graphene.String()
#     venezolanos = graphene.String()
#     canal_rpc_semana = graphene.String()
#     exclusion_rpc = graphene.String()
#     exclusion_lc = graphene.String()
#     novedad = graphene.String()
#     alternativa_aplicada_agr = graphene.String()
#     marca_agrupada_rgo = graphene.String()
#     producto_agrupado_origen = graphene.String()
#     f_aplicacion = graphene.Int()
#     bpo = graphene.String()
#     exclusion_alt = graphene.String()
#     activo = graphene.Int()
#     year = graphene.Int()
#     month = graphene.Int()
#     day = graphene.Int()
#     updated = graphene.Int()
#     modificacion_crud = graphene.Int()



class LastEvaluatedKeyPreaprobadosComercial(graphene.InputObjectType):
    clave = claveS()
    clave_ordenamiento = claveoS()

class PreaprobadosComercial(Model):
    class Meta:
        table_name = config.conf['preaprobados_comercial_table']
        # Specifies the region
        region = config.conf['region']
        # Specifies the write capacity
        write_capacity_units = config.conf['write_capacity_units']
        # Specifies the read capacity
        read_capacity_units = config.conf['read_capacity_units']

    clave = UnicodeAttribute(hash_key=True)
    clave_ordenamiento = UnicodeAttribute(range_key=True)
    corte = NumberAttribute(null=True, attr_name="corte")
    tipo_id = NumberAttribute(null=True, attr_name="tipo_id")
    nit_cliente = UnicodeAttribute(null=True, attr_name="nit_cliente")
    razon_social = UnicodeAttribute(null=True, attr_name="razon_social")
    segmento = UnicodeAttribute(null=True, attr_name="segmento")
    nro_operacion = UnicodeAttribute(null=True, attr_name="nro_operacion")
    prorroga = UnicodeAttribute(null=True, attr_name="prorroga")
    plazomax_prorroga = NumberAttribute(null=True, attr_name="plazomax_prorroga")
    ampl_cons = UnicodeAttribute(null=True, attr_name="ampl_cons")
    plazomin_ampl_cons = NumberAttribute(null=True, attr_name="plazomin_ampl_cons")
    plazomax_ampl_cons = NumberAttribute(null=True, attr_name="plazomax_ampl_cons")
    ampl_pg_cons = UnicodeAttribute(null=True, attr_name="ampl_pg_cons")
    plazomin_ampl_pg_cons = NumberAttribute(null=True, attr_name="plazomin_ampl_pg_cons")
    plazomax_ampl_pg_cons = NumberAttribute(null=True, attr_name="plazomax_ampl_pg_cons")
    ampl_mod = UnicodeAttribute(null=True, attr_name="ampl_mod")
    plazomin_ampl_mod = NumberAttribute(null=True, attr_name="plazomin_ampl_mod")
    plazomax_ampl_mod = NumberAttribute(null=True, attr_name="plazomax_ampl_mod")
    ampl_pg_mod = UnicodeAttribute(null=True, attr_name="ampl_pg_mod")
    plazomin_ampl_pg_mod = NumberAttribute(null=True, attr_name="plazomin_ampl_pg_mod")
    plazomax_ampl_pg_mod = NumberAttribute(null=True, attr_name="plazomax_ampl_pg_mod")
    ampl_reest = UnicodeAttribute(null=True, attr_name="ampl_reest")
    plazomin_ampl_reest = NumberAttribute(null=True, attr_name="plazomin_ampl_reest")
    plazomax_ampl_reest = NumberAttribute(null=True, attr_name="plazomax_ampl_reest")
    ampl_pg_reest = UnicodeAttribute(null=True, attr_name="ampl_pg_reest")
    plazomin_ampl_pg_reest = NumberAttribute(null=True, attr_name="plazomin_ampl_pg_reest")
    plazomax_ampl_pg_reest = NumberAttribute(null=True, attr_name="plazomax_ampl_pg_reest")
    bin = NumberAttribute(null=True, attr_name="bin")
    descripcion_bin = UnicodeAttribute(null=True, attr_name="descripcion_bin")
    cupo_minimo = NumberAttribute(null=True, attr_name="cupo_minimo")
    id_preaprobado = UnicodeAttribute(null=True, attr_name="id_preaprobado")
    mpio_exp_cc_cliente = UnicodeAttribute(null=True, attr_name="mpio_exp_cc_cliente")
    dpto_exp_cc_cliente = UnicodeAttribute(null=True, attr_name="dpto_exp_cc_cliente")
    subsegmento = UnicodeAttribute(null=True, attr_name="subsegmento")
    saldo_obligacion = NumberAttribute(null=True, attr_name="saldo_obligacion")
    plan = UnicodeAttribute(null=True, attr_name="plan")
    avales = UnicodeAttribute(null=True, attr_name="avales")
    desc_tipo_gtia = UnicodeAttribute(null=True, attr_name="desc_tipo_gtia")
    clave_larga = UnicodeAttribute(null=True, attr_name="clave_larga")
    clave_corta = UnicodeAttribute(null=True, attr_name="clave_corta")
    asignacion = UnicodeAttribute(null=True, attr_name="asignacion")
    control_pr = NumberAttribute(null=True, attr_name="control_pr")
    tipo_preaprobado = UnicodeAttribute(null=True, attr_name="tipo_preaprobado")
    nivel_alerta = UnicodeAttribute(null=True, attr_name="nivel_alerta")
    afectacion = UnicodeAttribute(null=True, attr_name="afectacion")
    linea_redescuento = UnicodeAttribute(null=True, attr_name="linea_redescuento")
    of_gte = NumberAttribute(null=True, attr_name="of_gte")
    calife_actual = UnicodeAttribute(null=True, attr_name="calife_actual")
    ciiucenie = NumberAttribute(null=True, attr_name="ciiucenie")
    saldo_cliente = NumberAttribute(null=True, attr_name="saldo_cliente")
    calife = UnicodeAttribute(null=True, attr_name="calife")
    califintmodred = UnicodeAttribute(null=True, attr_name="califintmodred")
    califi_real = UnicodeAttribute(null=True, attr_name="califi_real")
    max_mora_cli = NumberAttribute(null=True, attr_name="max_mora_cli")
    endeudamiento = NumberAttribute(null=True, attr_name="endeudamiento")
    marca_026 = UnicodeAttribute(null=True, attr_name="marca_026")
    altmora = NumberAttribute(null=True, attr_name="altmora")
    apl = UnicodeAttribute(null=True, attr_name="apl")
    fdesem = UnicodeAttribute(null=True, attr_name="fdesem")
    vdesem = NumberAttribute(null=True, attr_name="vdesem")
    seg_cuota_fut = NumberAttribute(null=True, attr_name="seg_cuota_fut")
    fecha_venc_def = UnicodeAttribute(null=True, attr_name="fecha_venc_def")
    f_prox_pago = UnicodeAttribute(null=True, attr_name="f_prox_pago")
    plazo = NumberAttribute(null=True, attr_name="plazo")
    gerenciado = UnicodeAttribute(null=True, attr_name="gerenciado")
    pcons = UnicodeAttribute(null=True, attr_name="pcons")
    regcons = UnicodeAttribute(null=True, attr_name="regcons")
    sector = UnicodeAttribute(null=True, attr_name="sector")
    subsector = UnicodeAttribute(null=True, attr_name="subsector")
    producto = UnicodeAttribute(null=True, attr_name="producto")
    fondo = UnicodeAttribute(null=True, attr_name="fondo")
    obl341 = UnicodeAttribute(null=True, attr_name="obl341")
    tipo_de_tasa = UnicodeAttribute(null=True, attr_name="tipo_de_tasa")
    tasa = NumberAttribute(null=True, attr_name="tasa")
    tasa_anterior = NumberAttribute(null=True, attr_name="tasa_anterior")
    id_rep_legal = NumberAttribute(null=True, attr_name="id_rep_legal")
    mpio_exp_cc_rep_legal = UnicodeAttribute(null=True, attr_name="mpio_exp_cc_rep_legal")
    dpto_exp_cc_rep_legal = UnicodeAttribute(null=True, attr_name="dpto_exp_cc_rep_legal")
    nombre_cli_rep = UnicodeAttribute(null=True, attr_name="nombre_cli_rep")
    marca_preaprobado = UnicodeAttribute(null=True, attr_name="marca_preaprobado")
    marca_garantia = UnicodeAttribute(null=True, attr_name="marca_garantia")
    tipo_de_amortizacion = UnicodeAttribute(null=True, attr_name="tipo_de_amortizacion")
    tipo_cuota = UnicodeAttribute(null=True, attr_name="tipo_cuota")
    tipo_tasa = UnicodeAttribute(null=True, attr_name="tipo_tasa")
    tamano_empresa = UnicodeAttribute(null=True, attr_name="tamano_empresa")
    nombre_garantia = UnicodeAttribute(null=True, attr_name="nombre_garantia")
    tipo_moneda = NumberAttribute(null=True, attr_name="tipo_moneda")
    bajo_monto = UnicodeAttribute(null=True, attr_name="bajo_monto")
    desc_tipo_fondo = UnicodeAttribute(null=True, attr_name="desc_tipo_fondo")
    proximo_pago = NumberAttribute(null=True, attr_name="proximo_pago")
    plan_desembolso = UnicodeAttribute(null=True, attr_name="plan_desembolso")
    paquete_consolidacion = UnicodeAttribute(null=True, attr_name="paquete_consolidacion")
    proceso_agil_consolidacion_pasivos = UnicodeAttribute(null=True, attr_name="proceso_agil_consolidacion_pasivos")
    cuenta = UnicodeAttribute(null=True, attr_name="cuenta")
    saldo_capital = NumberAttribute(null=True, attr_name="saldo_capital")
    cuotas_faltantes = NumberAttribute(null=True, attr_name="cuotas_faltantes")
    periodo_de_gracia_restante = UnicodeAttribute(null=True, attr_name="periodo_de_gracia_restante")
    spread = NumberAttribute(null=True, attr_name="spread")
    periodicidad_pago = UnicodeAttribute(null=True, attr_name="periodicidad_pago")
    modalidad = UnicodeAttribute(null=True, attr_name="modalidad")
    intereses_acumulados = NumberAttribute(null=True, attr_name="intereses_acumulados")
    otros_conceptos_acumulados = NumberAttribute(null=True, attr_name="otros_conceptos_acumulados")
    tasa_seguro_anual = NumberAttribute(null=True, attr_name="tasa_seguro_anual")
    cod_base_seg_vida = UnicodeAttribute(null=True, attr_name="cod_base_seg_vida")
    valor_desembolso_para_seg_vida = NumberAttribute(null=True, attr_name="valor_desembolso_para_seg_vida")
    mes_pago_fng = UnicodeAttribute(null=True, attr_name="mes_pago_fng")
    porcent_comision_fng = NumberAttribute(null=True, attr_name="porcent_comision_fng")
    mes_pago_fag = UnicodeAttribute(null=True, attr_name="mes_pago_fag")
    porcent_comision_fag = NumberAttribute(null=True, attr_name="porcent_comision_fag")
    saldo_total_vencido = NumberAttribute(null=True, attr_name="saldo_total_vencido")
    saldo_capital_vencido = NumberAttribute(null=True, attr_name="saldo_capital_vencido")
    saldo_interes_cte_vencido = NumberAttribute(null=True, attr_name="saldo_interes_cte_vencido")
    saldo_interes_mora_causados = NumberAttribute(null=True, attr_name="saldo_interes_mora_causados")
    saldo_int_mora_en_susp_causac = NumberAttribute(null=True, attr_name="saldo_int_mora_en_susp_causac")
    saldo_seguros_vencidos = NumberAttribute(null=True, attr_name="saldo_seguros_vencidos")
    saldo_otros_seguros = NumberAttribute(null=True, attr_name="saldo_otros_seguros")
    comision_exp = NumberAttribute(null=True, attr_name="comision_exp")
    iva_exp = NumberAttribute(null=True, attr_name="iva_exp")
    vlr_obligacion = NumberAttribute(null=True, attr_name="vlr_obligacion")
    pago_min_cons = NumberAttribute(null=True, attr_name="pago_min_cons")
    consdocdeu = NumberAttribute(null=True, attr_name="consdocdeu")
    nombre_usuario_dueno_tarea = UnicodeAttribute(null=True, attr_name="nombre_usuario_dueno_tarea")
    cod_abogado = UnicodeAttribute(null=True, attr_name="cod_abogado")
    nombre_abogado = UnicodeAttribute(null=True, attr_name="nombre_abogado")
    grupo_abogado = UnicodeAttribute(null=True, attr_name="grupo_abogado")
    perfil_abogado = UnicodeAttribute(null=True, attr_name="perfil_abogado")
    organizacion = NumberAttribute(null=True, attr_name="organizacion")
    pagares_a_consolidar = UnicodeAttribute(null=True, attr_name="pagares_a_consolidar")
    fecha1_pror = UnicodeAttribute(null=True, attr_name="fecha1_pror")
    fecha2_pror = UnicodeAttribute(null=True, attr_name="fecha2_pror")
    fecha3_pror = UnicodeAttribute(null=True, attr_name="fecha3_pror")
    dtf_ta = NumberAttribute(null=True, attr_name="dtf_ta")
    ibr_namv = NumberAttribute(null=True, attr_name="ibr_namv")
    ibr_natv = NumberAttribute(null=True, attr_name="ibr_natv")
    ibr_nasv = NumberAttribute(null=True, attr_name="ibr_nasv")
    ipc_vm = NumberAttribute(null=True, attr_name="ipc_vm")
    ipc_vac = NumberAttribute(null=True, attr_name="ipc_vac")
    ipc_va = NumberAttribute(null=True, attr_name="ipc_va")
    id_embargo = UnicodeAttribute(null=True, attr_name="id_embargo")
    descripcion_gestion = UnicodeAttribute(null=True, attr_name="descripcion_gestion")
    codigo_aprobador = UnicodeAttribute(null=True, attr_name="codigo_aprobador")
    f_gestion_cobdigit = UnicodeAttribute(null=True, attr_name="f_gestion_cobdigit")
    activo = NumberAttribute(null=True, attr_name="activo")
    year = NumberAttribute(null=True, attr_name="year")
    month = NumberAttribute(null=True, attr_name="month")
    day = NumberAttribute(null=True, attr_name="day")
    updated = NumberAttribute(null=True, attr_name="updated")
    modificacion_crud = NumberAttribute(null=True, attr_name="modificacion_crud")


def get_preaprobados_comercial( clave , clave_ordenamiento , limit = 100, ascendente = True, last_evaluated_key = None):

    if config.conf["tracklogs"]:
        logging.info("Consulta get_preaprobados_comercial con parametros: clave={}".format(clave))

    if clave_ordenamiento is not None:
        result = PreaprobadosComercial.query(hash_key = clave , range_key_condition = PreaprobadosComercial.clave_ordenamiento.startswith(clave_ordenamiento), filter_condition=PreaprobadosComercial.activo==1, limit=limit, scan_index_forward=ascendente,  last_evaluated_key=last_evaluated_key)
    else:
        result = PreaprobadosComercial.query( hash_key = clave , filter_condition=PreaprobadosComercial.activo==1, limit=limit, scan_index_forward=ascendente,  last_evaluated_key=last_evaluated_key)
    
    return list(result)


# class PreaprobadosComercialDataInput(graphene.InputObjectType):
#     clave = graphene.String()
#     clave_ordenamiento = graphene.String()
#     corte = graphene.Int()
#     tipo_id = graphene.Int()
#     nit_cliente = graphene.String()
#     razon_social = graphene.String()
#     segmento = graphene.String()
#     nro_operacion = graphene.String()
#     prorroga = graphene.String()
#     plazomax_prorroga = graphene.Int()
#     ampl_cons = graphene.String()
#     plazomin_ampl_cons = graphene.Int()
#     plazomax_ampl_cons = graphene.Int()
#     ampl_pg_cons = graphene.String()
#     plazomin_ampl_pg_cons = graphene.Int()
#     plazomax_ampl_pg_cons = graphene.Int()
#     ampl_mod = graphene.String()
#     plazomin_ampl_mod = graphene.Int()
#     plazomax_ampl_mod = graphene.Int()
#     ampl_pg_mod = graphene.String()
#     plazomin_ampl_pg_mod = graphene.Int()
#     plazomax_ampl_pg_mod = graphene.Int()
#     ampl_reest = graphene.String()
#     plazomin_ampl_reest = graphene.Int()
#     plazomax_ampl_reest = graphene.Int()
#     ampl_pg_reest = graphene.String()
#     plazomin_ampl_pg_reest = graphene.Int()
#     plazomax_ampl_pg_reest = graphene.Int()
#     bin = graphene.Int()
#     descripcion_bin = graphene.String()
#     cupo_minimo = graphene.Float()
#     id_preaprobado = graphene.String()
#     mpio_exp_cc_cliente = graphene.String()
#     dpto_exp_cc_cliente = graphene.String()
#     subsegmento = graphene.String()
#     saldo_obligacion = graphene.Float()
#     plan = graphene.String()
#     avales = graphene.String()
#     desc_tipo_gtia = graphene.String()
#     clave_larga = graphene.String()
#     clave_corta = graphene.String()
#     asignacion = graphene.String()
#     control_pr = graphene.Int()
#     tipo_preaprobado = graphene.String()
#     nivel_alerta = graphene.String()
#     afectacion = graphene.String()
#     linea_redescuento = graphene.String()
#     of_gte = graphene.Int()
#     calife_actual = graphene.String()
#     ciiucenie = graphene.Int()
#     saldo_cliente = graphene.Float()
#     calife = graphene.String()
#     califintmodred = graphene.String()
#     califi_real = graphene.String()
#     max_mora_cli = graphene.Int()
#     endeudamiento = graphene.Float()
#     marca_026 = graphene.String()
#     altmora = graphene.Float()
#     apl = graphene.String()
#     fdesem = graphene.String()
#     vdesem = graphene.Float()
#     seg_cuota_fut = graphene.Float()
#     fecha_venc_def = graphene.String()
#     f_prox_pago = graphene.String()
#     plazo = graphene.Int()
#     gerenciado = graphene.String()
#     pcons = graphene.String()
#     regcons = graphene.String()
#     sector = graphene.String()
#     subsector = graphene.String()
#     producto = graphene.String()
#     fondo = graphene.String()
#     obl341 = graphene.String()
#     tipo_de_tasa = graphene.String()
#     tasa = graphene.Float()
#     tasa_anterior = graphene.Float()
#     id_rep_legal = graphene.Int()
#     mpio_exp_cc_rep_legal = graphene.String()
#     dpto_exp_cc_rep_legal = graphene.String()
#     nombre_cli_rep = graphene.String()
#     marca_preaprobado = graphene.String()
#     marca_garantia = graphene.String()
#     tipo_de_amortizacion = graphene.String()
#     tipo_cuota = graphene.String()
#     tipo_tasa = graphene.String()
#     tamano_empresa = graphene.String()
#     nombre_garantia = graphene.String()
#     tipo_moneda = graphene.Int()
#     bajo_monto = graphene.String()
#     desc_tipo_fondo = graphene.String()
#     proximo_pago = graphene.Float()
#     plan_desembolso = graphene.String()
#     paquete_consolidacion = graphene.String()
#     proceso_agil_consolidacion_pasivos = graphene.String()
#     cuenta = graphene.String()
#     saldo_capital = graphene.Float()
#     cuotas_faltantes = graphene.Int()
#     periodo_de_gracia_restante = graphene.String()
#     spread = graphene.Float()
#     periodicidad_pago = graphene.String()
#     modalidad = graphene.String()
#     intereses_acumulados = graphene.Float()
#     otros_conceptos_acumulados = graphene.Float()
#     tasa_seguro_anual = graphene.Float()
#     cod_base_seg_vida = graphene.String()
#     valor_desembolso_para_seg_vida = graphene.Float()
#     mes_pago_fng = graphene.String()
#     porcent_comision_fng = graphene.Float()
#     mes_pago_fag = graphene.String()
#     porcent_comision_fag = graphene.Float()
#     saldo_total_vencido = graphene.Float()
#     saldo_capital_vencido = graphene.Float()
#     saldo_interes_cte_vencido = graphene.Float()
#     saldo_interes_mora_causados = graphene.Float()
#     saldo_int_mora_en_susp_causac = graphene.Float()
#     saldo_seguros_vencidos = graphene.Float()
#     saldo_otros_seguros = graphene.Float()
#     comision_exp = graphene.Float()
#     iva_exp = graphene.Float()
#     vlr_obligacion = graphene.Float()
#     pago_min_cons = graphene.Float()
#     consdocdeu = graphene.Int()
#     nombre_usuario_dueno_tarea = graphene.String()
#     cod_abogado = graphene.String()
#     nombre_abogado = graphene.String()
#     grupo_abogado = graphene.String()
#     perfil_abogado = graphene.String()
#     organizacion = graphene.Float()
#     pagares_a_consolidar = graphene.String()
#     fecha1_pror = graphene.String()
#     fecha2_pror = graphene.String()
#     fecha3_pror = graphene.String()
#     dtf_ta = graphene.Float()
#     ibr_namv = graphene.Float()
#     ibr_natv = graphene.Float()
#     ibr_nasv = graphene.Float()
#     ipc_vm = graphene.Float()
#     ipc_vac = graphene.Float()
#     ipc_va = graphene.Float()
#     id_embargo = graphene.String()
#     descripcion_gestion = graphene.String()
#     codigo_aprobador = graphene.String()
#     f_gestion_cobdigit = graphene.String()
#     activo = graphene.Int()
#     year = graphene.Int()
#     month = graphene.Int()
#     day = graphene.Int()
#     updated = graphene.Int()
#     modificacion_crud = graphene.Int()



class LastEvaluatedKeyTdcTasasPortal(graphene.InputObjectType):
    clave = claveS()
    clave_ordenamiento = claveoS()

class TdcTasasPortal(Model):
    class Meta:
        table_name = config.conf['tdc_tasas_portal_table']
        # Specifies the region
        region = config.conf['region']
        # Specifies the write capacity
        write_capacity_units = config.conf['write_capacity_units']
        # Specifies the read capacity
        read_capacity_units = config.conf['read_capacity_units']

    clave = UnicodeAttribute(hash_key=True)
    clave_ordenamiento = UnicodeAttribute(range_key=True)
    ingestion_year = NumberAttribute(null=True, attr_name="ingestion_year")
    ingestion_month = NumberAttribute(null=True, attr_name="ingestion_month")
    ingestion_day = NumberAttribute(null=True, attr_name="ingestion_day")
    costumer_number = UnicodeAttribute(null=True, attr_name="costumer_number")
    tipo_id_cliente = UnicodeAttribute(null=True, attr_name="tipo_id_cliente")
    id_cliente = UnicodeAttribute(null=True, attr_name="id_cliente")
    nombre_cliente = UnicodeAttribute(null=True, attr_name="nombre_cliente")
    tipo_id_amparador = UnicodeAttribute(null=True, attr_name="tipo_id_amparador")
    id_amparador = UnicodeAttribute(null=True, attr_name="id_amparador")
    nombre_amparador = UnicodeAttribute(null=True, attr_name="nombre_amparador")
    organizacion = NumberAttribute(null=True, attr_name="organizacion")
    cuenta = UnicodeAttribute(null=True, attr_name="cuenta")
    estado_cuenta = UnicodeAttribute(null=True, attr_name="estado_cuenta")
    block_code_1 = UnicodeAttribute(null=True, attr_name="block_code_1")
    block_code_2 = UnicodeAttribute(null=True, attr_name="block_code_2")
    dias_mora = NumberAttribute(null=True, attr_name="dias_mora")
    tarjeta = UnicodeAttribute(null=True, attr_name="tarjeta")
    bin = UnicodeAttribute(null=True, attr_name="bin")
    ultimos_4_numeros = UnicodeAttribute(null=True, attr_name="ultimos_4_numeros")
    franquicia = UnicodeAttribute(null=True, attr_name="franquicia")
    estado_tarjeta = UnicodeAttribute(null=True, attr_name="estado_tarjeta")
    block_code_tarjeta = UnicodeAttribute(null=True, attr_name="block_code_tarjeta")
    ciclo = NumberAttribute(null=True, attr_name="ciclo")
    fecha_ultimo_corte = UnicodeAttribute(null=True, attr_name="fecha_ultimo_corte")
    fecha_limite_de_pago = UnicodeAttribute(null=True, attr_name="fecha_limite_de_pago")
    fecha_proximo_corte = UnicodeAttribute(null=True, attr_name="fecha_proximo_corte")
    dias_proximo_corte = NumberAttribute(null=True, attr_name="dias_proximo_corte")
    transaciones_suspendidas = NumberAttribute(null=True, attr_name="transaciones_suspendidas")
    monto_transaciones_suspendidas = NumberAttribute(null=True, attr_name="monto_transaciones_suspendidas")
    deuda_total = NumberAttribute(null=True, attr_name="deuda_total")
    comisiones_deuda_total = NumberAttribute(null=True, attr_name="comisiones_deuda_total")
    intereses_deuda_total = NumberAttribute(null=True, attr_name="intereses_deuda_total")
    suma_comisiones_intereses_deuda_total = NumberAttribute(null=True, attr_name="suma_comisiones_intereses_deuda_total")
    capital_deuda_total = NumberAttribute(null=True, attr_name="capital_deuda_total")
    tasa_ponderada_deuda_total = NumberAttribute(null=True, attr_name="tasa_ponderada_deuda_total")
    tasa_pareto_deuda_total = NumberAttribute(null=True, attr_name="tasa_pareto_deuda_total")
    codigo_transaccion_deuda_total = UnicodeAttribute(null=True, attr_name="codigo_transaccion_deuda_total")
    pago_minimo_pendiente = NumberAttribute(null=True, attr_name="pago_minimo_pendiente")
    comisiones_pago_minimo_pendiente = NumberAttribute(null=True, attr_name="comisiones_pago_minimo_pendiente")
    intereses_pago_minimo_pendiente = NumberAttribute(null=True, attr_name="intereses_pago_minimo_pendiente")
    suma_comisiones_intereses_pago_minimo_pendiente = NumberAttribute(null=True, attr_name="suma_comisiones_intereses_pago_minimo_pendiente")
    capital_pago_minimo_pendiente = NumberAttribute(null=True, attr_name="capital_pago_minimo_pendiente")
    tasa_ponderada_pago_minimo = NumberAttribute(null=True, attr_name="tasa_ponderada_pago_minimo")
    tasa_pareto_pago_minimo = NumberAttribute(null=True, attr_name="tasa_pareto_pago_minimo")
    codigo_transaccion_pago_minimo = UnicodeAttribute(null=True, attr_name="codigo_transaccion_pago_minimo")
    plazo_maximo = UnicodeAttribute(null=True, attr_name="plazo_maximo")
    plazo_rango = UnicodeAttribute(null=True, attr_name="plazo_rango")
    fecha_registro = UnicodeAttribute(null=True, attr_name="fecha_registro")
    hora_registro = UnicodeAttribute(null=True, attr_name="hora_registro")
    fecha_saldos = UnicodeAttribute(null=True, attr_name="fecha_saldos")
    fecha_reg = NumberAttribute(null=True, attr_name="fecha_reg")
    tasa_politica = NumberAttribute(null=True, attr_name="tasa_politica")
    year = NumberAttribute(null=True, attr_name="year")
    month = NumberAttribute(null=True, attr_name="month")
    activo = NumberAttribute(null=True, attr_name="activo")
    updated = NumberAttribute(null=True, attr_name="updated")
    modificacion_crud = NumberAttribute(null=True, attr_name="modificacion_crud")


def get_tdc_tasas_portal( clave , clave_ordenamiento , limit = 100, ascendente = True, last_evaluated_key = None):

    if config.conf["tracklogs"]:
        logging.info("Consulta get_tdc_tasas_portal con parametros: clave={}".format(clave))

    if clave_ordenamiento is not None:
        result = TdcTasasPortal.query(hash_key = clave , range_key_condition = TdcTasasPortal.clave_ordenamiento.startswith(clave_ordenamiento), filter_condition=TdcTasasPortal.activo==1, limit=limit, scan_index_forward=ascendente,  last_evaluated_key=last_evaluated_key)
    else:
        result = TdcTasasPortal.query( hash_key = clave , filter_condition=TdcTasasPortal.activo==1, limit=limit, scan_index_forward=ascendente,  last_evaluated_key=last_evaluated_key)
    
    return list(result)


# class TdcTasasPortalDataInput(graphene.InputObjectType):
#     clave = graphene.String()
#     clave_ordenamiento = graphene.String()
#     ingestion_year = graphene.Int()
#     ingestion_month = graphene.Int()
#     ingestion_day = graphene.Int()
#     costumer_number = graphene.String()
#     tipo_id_cliente = graphene.String()
#     id_cliente = graphene.String()
#     nombre_cliente = graphene.String()
#     tipo_id_amparador = graphene.String()
#     id_amparador = graphene.String()
#     nombre_amparador = graphene.String()
#     organizacion = graphene.Float()
#     cuenta = graphene.String()
#     estado_cuenta = graphene.String()
#     block_code_1 = graphene.String()
#     block_code_2 = graphene.String()
#     dias_mora = graphene.Float()
#     tarjeta = graphene.String()
#     bin = graphene.String()
#     ultimos_4_numeros = graphene.String()
#     franquicia = graphene.String()
#     estado_tarjeta = graphene.String()
#     block_code_tarjeta = graphene.String()
#     ciclo = graphene.Float()
#     fecha_ultimo_corte = graphene.String()
#     fecha_limite_de_pago = graphene.String()
#     fecha_proximo_corte = graphene.String()
#     dias_proximo_corte = graphene.Float()
#     transaciones_suspendidas = graphene.Float()
#     monto_transaciones_suspendidas = graphene.Float()
#     deuda_total = graphene.Float()
#     comisiones_deuda_total = graphene.Float()
#     intereses_deuda_total = graphene.Float()
#     suma_comisiones_intereses_deuda_total = graphene.Float()
#     capital_deuda_total = graphene.Float()
#     tasa_ponderada_deuda_total = graphene.Float()
#     tasa_pareto_deuda_total = graphene.Float()
#     codigo_transaccion_deuda_total = graphene.String()
#     pago_minimo_pendiente = graphene.Float()
#     comisiones_pago_minimo_pendiente = graphene.Float()
#     intereses_pago_minimo_pendiente = graphene.Float()
#     suma_comisiones_intereses_pago_minimo_pendiente = graphene.Float()
#     capital_pago_minimo_pendiente = graphene.Float()
#     tasa_ponderada_pago_minimo = graphene.Float()
#     tasa_pareto_pago_minimo = graphene.Float()
#     codigo_transaccion_pago_minimo = graphene.String()
#     plazo_maximo = graphene.String()
#     plazo_rango = graphene.String()
#     fecha_registro = graphene.String()
#     hora_registro = graphene.String()
#     fecha_saldos = graphene.String()
#     fecha_reg = graphene.Float()
#     tasa_politica = graphene.Float()
#     year = graphene.Int()
#     month = graphene.Int()
#     activo = graphene.Int()
#     updated = graphene.Int()
#     modificacion_crud = graphene.Int()


